apiVersion: apps/v1
kind: ConfigMap
metadata:
    name: my-test-pod-env
data:
    {{- range $key, $value := .Values.global.cluster.data.mytestpodenv }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}